### ISSUE TITLE
account create problem still

### ISSUE THREAD

**Issue by djsushilkumar** [JosephChuks/HestiaCP-WHMCS-Module#1]
Order Accept Encountered Problems
Function Not Supported by Module

**Comment by JosephChuks** [comment]
I haven't encountered error with order.
![image_2024-05-21_171001122](https://github.com/JosephChuks/HestiaCP-WHMCS-Module/assets/61961733/66b5d26a-bce8-4b8e-a195-9c12f7b20c12)

The error may be coming due to package name issue.
Edit the products, on the `module settings` tab, add the name of the package you set in hestiacp for the product,

![image_2024-05-21_171508236](https://github.com/JosephChuks/HestiaCP-WHMCS-Module/assets/61961733/d77aa9be-cadf-446a-aeaf-1a8d823a30d2)

![image_2024-05-21_171532940](https://github.com/JosephChuks/HestiaCP-WHMCS-Module/assets/61961733/683b688a-3757-4fdf-aa93-5ebf0f43c696)

**Comment by djsushilkumar** [comment]
thanks plz make advance module like cpanel

**Comment by djsushilkumar** [comment]
package name 
IP address 
ssh access   tick to grant

no  option is 
![a](https://github.com/JosephChuks/HestiaCP-WHMCS-Module/assets/97604988/df4c09b6-3b42-4477-8621-ec922de495a9)
found in my whmcs product module setting

**Comment by JosephChuks** [comment]
I just updated `hestia.php`. Try the updated file and check.

Also, the file name should be `hestia.php` and not `hestiacp.php`

**Comment by enoquesilvax** [comment]
I have a problem, everything is working ok, but when creating the account, following the entire tutorial you wrote, the user account does not create, how can I solve it?

**Comment by JosephChuks** [comment]
> I have a problem, everything is working ok, but when creating the account, following the entire tutorial you wrote, the user account does not create, how can I solve it?

The issue might be coming from **Package** 
Check the name of the package on the whmcs product matches with the package name on your hestia control panel

**Comment by enoquesilvax** [comment]
Even with the correct package name, the whmcs module is unable to create the account.

**Comment by enoquesilvax** [comment]
To do a new installation, follow step by step and make sure people really have to paste their own admin user's api in the users / click on the admin user / in the access keys to create a new key. Afterwards, just set the hash of WHMCS "access_key:secret_key", with these two points itself.

**Comment by JosephChuks** [comment]
> To do a new installation, follow step by step and make sure people really have to paste their own admin user's api in the users / click on the admin user / in the access keys to create a new key. Afterwards, just set the hash of WHMCS "access_key:secret_key", with these two points itself.

The process is explained in the readme file. Make sure your server allows outgoing requests on your HestiaCP port.
